<?php

declare(strict_types=1);

namespace NebulaToken;

use Closure;

/**
 * NEBULA engine — SPECIFICATION.md §5–§6.
 *
 * Every protocol outcome is a returned value ([N-29]); anything the store
 * throws propagates untouched so the caller fails closed ([N-20]).
 */
final class NebulaEngine
{
    /** @var array<string, string> */
    private readonly array $peppers;
    private readonly string $activeKid;
    private readonly RefreshTokenStore $store;
    private readonly int $absoluteTtl;
    private readonly int $idleTtl;
    private readonly int $reuseGrace;
    private readonly Closure $clock;

    /**
     * @param array<string, string> $peppers Map kid → pepper secret. Each secret is a
     *                                       cryptographic key of at least
     *                                       MIN_PEPPER_LENGTH bytes, held in env/KMS
     *                                       and generated by a CSPRNG ([N-23]).
     * @param Closure():int|null    $clock   Injectable clock, unix seconds ([N-3]).
     *
     * @throws NebulaConfigException on any violation of §5.
     */
    public function __construct(
        #[\SensitiveParameter] array $peppers,
        string $activeKid,
        RefreshTokenStore $store,
        int $absoluteTtlSeconds = Nebula::DEFAULT_ABSOLUTE_TTL,
        int $idleTtlSeconds = Nebula::DEFAULT_IDLE_TTL,
        int $reuseGraceSeconds = Nebula::DEFAULT_REUSE_GRACE,
        ?Closure $clock = null,
    ) {
        $copy = [];
        foreach ($peppers as $kid => $secret) {
            // An all-digit kid arrives here as an int array key; §2 measures the
            // string form, so normalise before validating it.
            $kid = (string) $kid;
            if (preg_match('/\A[A-Za-z0-9_-]{1,' . Nebula::MAX_KID_LENGTH . '}\z/', $kid) !== 1) {
                throw new NebulaConfigException(sprintf(
                    'kid "%s" must be 1-%d characters from [A-Za-z0-9_-]',
                    $kid,
                    Nebula::MAX_KID_LENGTH,
                ));
            }
            // [N-11] the HMAC key is the pepper encoded as UTF-8, so a value
            // that has no UTF-8 encoding — a lone surrogate out of a JSON
            // secrets file, a Latin-1 byte string — is not a usable key: each
            // runtime would substitute something different and derive a
            // different key from the same configured value. §5 resolves it by
            // failing construction everywhere. The message never quotes the
            // secret ([N-14]).
            if (!Nebula::isWellFormedUtf8($secret)) {
                throw new NebulaConfigException(sprintf(
                    'pepper "%s" must be a string with a UTF-8 encoding (no unpaired surrogate)',
                    $kid,
                ));
            }
            if (strlen($secret) < Nebula::MIN_PEPPER_LENGTH) {
                // strlen() is a byte count of the UTF-8 encoding proved above:
                // MIN_PEPPER_LENGTH is bytes, not characters ([N-1]), so a
                // 16-character CJK passphrase passes and a 31-byte ASCII one
                // does not.
                throw new NebulaConfigException(sprintf(
                    'pepper "%s" must be at least %d bytes',
                    $kid,
                    Nebula::MIN_PEPPER_LENGTH,
                ));
            }
            $copy[$kid] = $secret;
        }
        if (!isset($copy[$activeKid])) {
            throw new NebulaConfigException(sprintf('activeKid "%s" not present in peppers', $activeKid));
        }
        if ($absoluteTtlSeconds <= 0) {
            throw new NebulaConfigException('absoluteTtlSeconds must be > 0');
        }
        if ($idleTtlSeconds <= 0) {
            throw new NebulaConfigException('idleTtlSeconds must be > 0');
        }
        if ($reuseGraceSeconds < 0) {
            throw new NebulaConfigException('reuseGraceSeconds must be >= 0');
        }

        // [N-24] the configuration is copied. PHP arrays are values, so this
        // assignment already detaches the engine from the caller's array —
        // mutating it afterwards cannot weaken the engine.
        $this->peppers = $copy;
        $this->activeKid = $activeKid;
        $this->store = $store;
        $this->absoluteTtl = $absoluteTtlSeconds;
        $this->idleTtl = $idleTtlSeconds;
        $this->reuseGrace = $reuseGraceSeconds;
        $this->clock = $clock ?? static fn (): int => time();
    }

    /**
     * Issue the first token of a new family ([N-25]). Call at login.
     *
     * `$deviceId === null` (unbound) is distinct from `''`, which is a real
     * binding like any other string.
     *
     * @throws NebulaConfigException if $deviceId is not valid UTF-8 ([N-12])
     */
    public function issue(string $userId, #[\SensitiveParameter] ?string $deviceId = null): IssueResult
    {
        // [N-12] at issue the value comes from the application, so surface the
        // defect at the call site rather than minting a binding that nothing
        // can ever satisfy. hashDeviceId() performs the same check.
        $deviceHash = $deviceId !== null ? Nebula::hashDeviceId($this->activePepper(), $deviceId) : null;

        $now = ($this->clock)();
        $familyId = bin2hex(random_bytes(16));
        $familyExpiresAt = $now + $this->absoluteTtl;
        [$token, $record] = $this->mint($userId, $familyId, 0, $deviceHash, $familyExpiresAt, $now);

        // A throwing insert must not produce a token for state never written ([N-20]).
        $this->store->insert($record);

        return new IssueResult(
            token: $token,
            userId: $userId,
            familyId: $familyId,
            generation: 0,
            expiresAt: $familyExpiresAt,
            idleExpiresAt: $record->idleExpiresAt,
        );
    }

    /**
     * Renders the engine's shape without its secrets ([N-46]).
     *
     * PHP's debug output prints private properties, so the default rendering of
     * this object hands every pepper to `var_dump()`, a `dd()`, a `dump()` and
     * any framework error page that walks an object graph. The pepper is the key
     * that protects every session of every user, so keep it out of all of them.
     *
     * KNOWN GAP: this hook is consulted by `var_dump()` and by the debuggers
     * built on it, but NOT by `print_r()` or `var_export()`, which walk the
     * property table directly and print private properties regardless. PHP
     * offers no hook for those two, so closing it means the pepper map must
     * stop being a plain property. Until then, `print_r($engine, true)` into a
     * log line still leaks; the `#[\SensitiveParameter]` attributes on the
     * constructor and on the token/device arguments close the adjacent
     * exception-trace channel, which `zend.exception_ignore_args=0` leaves open
     * by default in php.ini-development.
     *
     * @return array<string, mixed>
     */
    public function __debugInfo(): array
    {
        return [
            'kids' => array_keys($this->peppers),
            'peppers' => '[redacted]',
            'activeKid' => $this->activeKid,
            'store' => get_class($this->store),
            'absoluteTtl' => $this->absoluteTtl,
            'idleTtl' => $this->idleTtl,
            'reuseGrace' => $this->reuseGrace,
        ];
    }

    /**
     * Exchange a refresh token for its successor ([N-26]). The order of checks is normative.
     *
     * php:S1142 wants at most three returns. [N-26] mandates ten checks in a
     * fixed order, "returning the first failure" — early return is not a style
     * choice here, it is the specification, and [N-28] makes the resulting order
     * observable. The two parts worth extracting already are (handleReuse for
     * step 5, rotate for step 10), matching the TypeScript reference; what is
     * left is the [N-26] table, and the step numbers in the trailing comments
     * are how a reader checks it against the spec.
     */
    public function refresh(
        #[\SensitiveParameter] string $token,
        #[\SensitiveParameter] ?string $deviceId = null,
    ): RefreshResult // NOSONAR(php:S1142)
    {
        $parsed = Nebula::parseToken($token);                                   // 1
        if ($parsed === null) {
            return RefreshResult::failure(ErrorCode::Malformed);
        }

        if (!isset($this->peppers[$parsed->kid])) {                             // 2
            return RefreshResult::failure(ErrorCode::UnknownKid);
        }

        $record = $this->store->findBySelector($parsed->selector);              // 3
        if ($record === null) {
            return RefreshResult::failure(ErrorCode::NotFound);
        }

        $recordPepper = $this->peppers[$record->kid] ?? null;                   // 4 — the RECORD's kid
        if ($recordPepper === null) {
            return RefreshResult::failure(ErrorCode::UnknownKid);               // [N-27]
        }
        $presented = Nebula::hashVerifier($recordPepper, $parsed->verifier);
        if (!Nebula::constantTimeEqualHex($presented, $record->verifierHash)) {
            // [N-28] no family revocation here: knowledge of a selector alone
            // must never be enough to destroy a session.
            return RefreshResult::failure(ErrorCode::VerifierMismatch, $record);
        }

        $now = ($this->clock)();

        if ($record->status === TokenStatus::Rotated) {                         // 5
            return $this->handleReuse($record, $recordPepper, $deviceId, $now);
        }
        if ($record->status === TokenStatus::Revoked) {                         // 6
            return RefreshResult::failure(ErrorCode::Revoked, $record);
        }

        if ($now >= $record->familyExpiresAt) {                                 // 7
            $this->store->revokeFamily($record->familyId);
            return RefreshResult::failure(ErrorCode::ExpiredAbsolute, $record);
        }
        if ($now >= $record->idleExpiresAt) {                                   // 8
            $this->store->revokeFamily($record->familyId);
            return RefreshResult::failure(ErrorCode::ExpiredIdle, $record);
        }

        if ($record->deviceIdHash !== null                                      // 9 — the RECORD's pepper
            && !$this->deviceMatches($record, $recordPepper, $deviceId)) {
            $this->store->revokeFamily($record->familyId);
            return RefreshResult::failure(ErrorCode::DeviceMismatch, $record);
        }

        return $this->rotate($record, $deviceId, $now, TokenStatus::Active, $now); // 10
    }

    /**
     * Revoke the family a token belongs to ([N-36]).
     *
     * Authenticated: steps 1–4 of [N-26] are performed exactly as in refresh(),
     * because the selector is a public lookup key and must not by itself be a
     * capability to terminate a session. Succeeds whatever the record's status,
     * so a client can still log out with a token already rotated or revoked.
     *
     * Takes no device identifier and performs no sender-binding check ([N-36]
     * specifies steps 1-4 of [N-26] and no sender-binding step), because logout
     * must keep working for a client that can no longer produce its device
     * identifier. The operation is already authenticated by the verifier proof.
     *
     * php:S1142: the four returns are steps 1-4 of [N-26], each returning the
     * first failure. Same reasoning as refresh() above.
     */
    public function revokeToken(#[\SensitiveParameter] string $token): RevokeResult // NOSONAR(php:S1142)
    {
        $parsed = Nebula::parseToken($token);
        if ($parsed === null) {
            return RevokeResult::failure(ErrorCode::Malformed);
        }
        if (!isset($this->peppers[$parsed->kid])) {
            return RevokeResult::failure(ErrorCode::UnknownKid);
        }

        $record = $this->store->findBySelector($parsed->selector);
        if ($record === null) {
            return RevokeResult::failure(ErrorCode::NotFound);
        }

        $recordPepper = $this->peppers[$record->kid] ?? null;
        if ($recordPepper === null) {
            return RevokeResult::failure(ErrorCode::UnknownKid);
        }
        $presented = Nebula::hashVerifier($recordPepper, $parsed->verifier);
        if (!Nebula::constantTimeEqualHex($presented, $record->verifierHash)) {
            // [N-39] the record was resolved above, so this refusal is
            // attributable. An unauthenticated attempt to terminate somebody's
            // session is exactly the event an operator needs to see, and the
            // selector alone will not identify the victim.
            return RevokeResult::failure(ErrorCode::VerifierMismatch, $record);
        }

        // No sender-binding step ([N-36]): revocation takes no device identifier.
        $revoked = $this->store->revokeFamily($record->familyId);

        return RevokeResult::success($record->userId, $record->familyId, $revoked);
    }

    /**
     * Revoke a whole family by its server-side identifier ([N-37]).
     * Requires no token; the caller is responsible for authorising it.
     */
    public function revokeFamily(string $familyId): int
    {
        return $this->store->revokeFamily($familyId);
    }

    /** Revoke every session of a user ([N-37]). Returns how many records changed. */
    public function revokeAllForUser(string $userId): int
    {
        return $this->store->revokeUser($userId);
    }

    // ── Private ────────────────────────────────────────────────────────────

    /**
     * Step 5 of [N-26]: a `rotated` record was presented ([N-30], [N-31]).
     *
     * php:S1142: the four returns are the grace-retry decision tree of [N-30] —
     * outside grace, inside grace with a live successor, device mismatch, and
     * the reuse path that revokes the family. Each is a distinct normative
     * outcome returning the first failure, exactly as in refresh().
     */
    private function handleReuse( // NOSONAR(php:S1142)
        TokenRecord $record,
        string $recordPepper,
        ?string $deviceId,
        int $now,
    ): RefreshResult {
        // [N-30] preconditions 1-4 and 6, spelled out inline so that both the
        // reader and a static analyser can see rotatedAt and replacedBySelector
        // narrowed to non-null inside the block. Condition 6 (now <
        // familyExpiresAt) is what stops a grace retry from minting a token
        // whose family is already past its absolute ceiling.
        if ($this->reuseGrace > 0
            && $record->rotatedAt !== null
            && $now - $record->rotatedAt <= $this->reuseGrace
            && $record->replacedBySelector !== null
            && $now < $record->familyExpiresAt
        ) {
            $successor = $this->store->findBySelector($record->replacedBySelector);
            // [N-30] precondition 5: any evidence that the successor was already
            // used turns the retry back into a theft signal.
            if ($successor !== null && $successor->status === TokenStatus::Active) {
                if ($record->deviceIdHash !== null && !$this->deviceMatches($record, $recordPepper, $deviceId)) {
                    $this->store->revokeFamily($record->familyId);
                    return RefreshResult::failure(ErrorCode::DeviceMismatch, $record);
                }
                // Compare-and-set: exactly one concurrent retry may consume the
                // unused successor. The loser mints nothing and reports CONFLICT.
                if (!$this->store->revokeIfActive($successor->selector)) {
                    return RefreshResult::failure(ErrorCode::Conflict, $record);
                }
                // The original rotatedAt is preserved: the window is anchored to
                // the first rotation and cannot be walked forward ([N-30]).
                return $this->rotate($record, $deviceId, $now, TokenStatus::Rotated, $record->rotatedAt);
            }
        }

        $this->store->revokeFamily($record->familyId);

        return RefreshResult::failure(ErrorCode::ReuseDetected, $record);
    }

    /** Rotation of a record with a given $fromStatus ([N-34]). */
    private function rotate(
        TokenRecord $record,
        ?string $deviceId,
        int $now,
        TokenStatus $fromStatus,
        int $rotatedAt,
    ): RefreshResult {
        // Re-hash with the ACTIVE pepper: this is what migrates a device
        // binding forward across a pepper rotation ([N-33] step 4).
        $deviceHash = ($record->deviceIdHash !== null && $deviceId !== null)
            ? Nebula::hashDeviceId($this->activePepper(), $deviceId)
            : $record->deviceIdHash;

        [$token, $next] = $this->mint(
            $record->userId,
            $record->familyId,
            $record->generation + 1,
            $deviceHash,
            $record->familyExpiresAt,
            $now,
        );
        $this->store->insert($next);

        if (!$this->store->markRotated($record->selector, $fromStatus, $rotatedAt, $next->selector)) {
            // [N-34] step 5: a concurrent refresh won the compare-and-set. Clean
            // up the successor we inserted and report a retryable conflict —
            // never a token, and nothing else is revoked ([N-35]).
            $this->store->revokeIfActive($next->selector);
            return RefreshResult::failure(ErrorCode::Conflict, $record);
        }

        return RefreshResult::success($next, $token);
    }

    /**
     * Mint a fresh record and its wire token ([N-33]).
     *
     * @return array{0: string, 1: TokenRecord}
     */
    private function mint(
        string $userId,
        string $familyId,
        int $generation,
        ?string $deviceIdHash,
        int $familyExpiresAt,
        int $now,
    ): array {
        // random_bytes() is the platform CSPRNG and throws rather than falling
        // back to a weaker source ([N-43]).
        $selector = Nebula::b64urlEncode(random_bytes(Nebula::SELECTOR_BYTES));
        $verifier = random_bytes(Nebula::VERIFIER_BYTES);
        $record = new TokenRecord(
            selector: $selector,
            verifierHash: Nebula::hashVerifier($this->activePepper(), $verifier),
            kid: $this->activeKid,
            familyId: $familyId,
            generation: $generation,
            userId: $userId,
            deviceIdHash: $deviceIdHash,
            createdAt: $now,
            familyExpiresAt: $familyExpiresAt,
            idleExpiresAt: min($now + $this->idleTtl, $familyExpiresAt),
        );
        $token = Nebula::PREFIX . '.' . $this->activeKid . '.' . $selector . '.' . Nebula::b64urlEncode($verifier);

        return [$token, $record];
    }

    /** Sender binding ([N-32]), hashed with the record's own pepper. */
    private function deviceMatches(TokenRecord $record, string $recordPepper, ?string $deviceId): bool
    {
        if ($deviceId === null || $record->deviceIdHash === null) {
            return false;
        }
        // [N-12] on the attacker-reachable path a device id that is not valid
        // UTF-8 is a binding failure, never an exception.
        if (!Nebula::isWellFormedUtf8($deviceId)) {
            return false;
        }

        return Nebula::constantTimeEqualHex(
            Nebula::hashDeviceId($recordPepper, $deviceId),
            $record->deviceIdHash,
        );
    }

    private function activePepper(): string
    {
        return $this->peppers[$this->activeKid];
    }
}
